VTimezone Recurrence parsing
Neuvernetzung/ts-ics pull request #48
Opened 2023-10-31 22:14 UTC by dbondarchuk

Added parsing VTimezone props to extract the offset for the specific date

This code is built with the help of https://github.com/mangstadt/biweekly as a reference.

It can be a ground-up work for adding support for the recurring events

2023-10-31 22:59 UTC, dbondarchuk commented
@timheerwagen let's have a look on proper timezones :)

2023-11-01 08:58 UTC, timheerwagen requested changes
A huge thanks for this comprehensive Contribution. Due to the fact that recurrence has now been introduced, it would be of advantage to use the whole thing for calendars, events etc. as well.

The utils for generating the recurrence and timezone would certainly be better off in src/utils, instead of src/lib/parse/utils. Because I would also like to provide a function which can be used independently similar to "https://github.com/jkbrzt/rrule" rrule.all or rrule.between.

The function could have following type: (rule: VEventRecurrenceRule, options: {start?:Date;end?:Date) => Date[]

We also need tests to cover the complex functionality of recurrence.

2023-11-01 08:58 UTC, timheerwagen commented on package.json
> +    "@datastructures-js/priority-queue": "^6.3.0",
Is there a way without this extra dependency? Why exactly do we need this?

2023-11-01 08:58 UTC, timheerwagen commented on src/lib/parse/utils/recurrence/compoundIterator.ts
Is there a reason why you use classes? I would prefer functions.

2023-11-01 08:58 UTC, timheerwagen commented on src/lib/parse/utils/recurrence/dateTimeBuilder.ts
Same here.

2023-11-01 08:58 UTC, timheerwagen commented on src/lib/parse/utils/recurrence/filter.ts
Why are you using bitwise here? Are there any alternatives?

2023-11-01 08:58 UTC, timheerwagen commented on src/lib/parse/utils/recurrence/generators.ts
> +  // TODO(msamuel): does this work?
Please remove unused comments from the other package

2023-11-01 08:58 UTC, timheerwagen commented on src/lib/parse/utils/timezone/offset.ts
> +export const minutesToMillis = (minutes: number): number => minutes * 60 * 1000;
Just use hoursToMilliseconds and minutesToMilliseconds from date-fns for consistency please.

2023-11-01 16:04 UTC, dbondarchuk commented
Maybe we can use https://github.com/jkbrzt/rrule lib to do everything for us?

2023-11-01 16:20 UTC, timheerwagen commented
During the development of version 1.0.0 I already tried this, but I didn't like it. Because Rrule has a lot of things that we don't need, like its own parsing, etc. In my opinion there must be an easier way to generate this recurring dates.

It is certainly worth creating this functionality from scratch yourself. And besides, I don't like their license.

2023-11-06 11:41 UTC, timheerwagen commented
After a lot of hard work, I have now succeeded in providing my own functionality for RRule, including tests. Please have a look at the current development branch to check that I haven't forgotten anything. The feature will be released later in v1.2.0.

2023-11-06 17:30 UTC, dbondarchuk commented
That looks great!

2023-11-06 17:30 UTC, closed without merging